trigger:
- main # Se ejecuta en cada cambio a la rama 'main'

pool:
  vmImage: 'ubuntu-latest' # Uso el agente de Linux

steps:
- task: UsePythonVersion@0
  displayName: 'Establecer versión de Python'
  inputs:
    versionSpec: '3.x' # Se puede cambiar esto a una versión especifica como '3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar Dependencias (requirements.txt)'

- script: |
    # Este paso es OPCIONAL, se usa solo si se tiene pruebas unitarias (tests)
    # Reemplaza 'pytest' si se uso otra libreria como 'unittest'
    pip install pytest
    pytest
  displayName: 'Ejecutar Pruebas (Opcional)'
  
# Si se necesita construir un Docker Image o desplegar a Azure App Service, 
# se añadirian mas pasos aquí, pero con esto el pipeline basico ya funciona