# Python package
# Create and test a Python package on a single Python version (3.11).

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python311:              # <--- SOLO UNA ENTRADA EN LA MATRIZ
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies (Flask, etc.)'

- script: |
    # Instala pytest y su extensión para reportar resultados en Azure DevOps
    pip install pytest pytest-azurepipelines
    # Ejecuta tus pruebas unitarias
    pytest
  displayName: 'Run tests with pytest'

# Paso para publicar el código probado como un artefacto
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'flask-app-$(python.version)'
    publishLocation: 'Container'
  displayName: 'Publish Application Artifact'