trigger:
- main

variables:
  azureServiceConnectionId: "Conexion-Flask-Students"
  webAppName: "mi-flask-app-2025"
  # Grupo de Recursos: RG-MIAppFlask (El más probable para superar el CODE: 404)
  resourceGroup: "RG-MIAppFlask" 
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.10'

# ===============================================================
# Etapa de Build
# ===============================================================
stages:
  - stage: Build
    displayName: "1. Build Stage"
    jobs:
      - job: BuildJob
        displayName: "Build and Package"
        pool:
          vmImage: 'ubuntu-latest' # <--- CAMBIO CRÍTICO: Usar agente de Azure
        steps:
          # Usamos la tarea para asegurar la versión de Python
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            workingDirectory: $(projectRoot)
            displayName: "Install Python dependencies"

          - task: ArchiveFiles@2
            displayName: "Archive project files"
            inputs:
              rootFolderOrFile: "$(projectRoot)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: "$(Build.ArtifactStagingDirectory)/drop.zip"
              replaceExistingArchive: true

          - publish: "$(Build.ArtifactStagingDirectory)/drop.zip"
            artifact: drop
            displayName: "Publish deployment package"

# ===============================================================
# Etapa de Test (Usará Ubuntu para mayor compatibilidad de comandos)
# ===============================================================
  - stage: Test
    displayName: "2. Run Automated Tests"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: RunTests
        displayName: "Execute Tests and Generate Reports"
        pool:
          vmImage: 'ubuntu-latest' # <--- CAMBIO CRÍTICO: Usar agente de Azure
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
              addToPath: true
            displayName: 'Use Python $(pythonVersion)'
          
          - download: current
            artifact: drop
            displayName: 'Download build artifacts for testing'
            
          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pytest pytest-cov unittest-xml-reporting
            workingDirectory: $(projectRoot) 
            displayName: "Install test dependencies"

          - script: |
              echo "INICIANDO EJECUCIÓN DE PRUEBAS AUTOMÁTICAS"
              python -m pytest tests/ -v --cov=./ --cov-report=xml:coverage.xml --cov-report=html:coverage_html --junitxml=test-results.xml
            displayName: "Run Tests with Coverage and Metrics"

          - task: PublishTestResults@2
            displayName: "Publish Test Results to Azure"
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "test-results.xml"
              testRunTitle: "Don Galleto - Test Results"
              failTaskOnFailedTests: true
              
          - task: PublishCodeCoverageResults@1
            displayName: "Publish Code Coverage Report"
            inputs:
              codeCoverageTool: "Cobertura"
              summaryFileLocation: "$(projectRoot)/coverage.xml"

# ===============================================================
# Etapa de Deploy
# ===============================================================
  - stage: Deploy
    displayName: "3. Deploy Web App"
    dependsOn: Test
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: "Deploy to Azure Web App Linux"
        pool:
          vmImage: 'ubuntu-latest' # <--- CAMBIO CRÍTICO: Usar agente de Azure
        steps:
          - download: current
            artifact: drop
            displayName: "Download build artifacts"

          # Habilitar logs
          - task: AzureCLI@2
            displayName: "Enable Application Logging"
            inputs:
              azureSubscription: "$(azureServiceConnectionId)"
              scriptType: "bash" # Cambiamos a bash, que es el shell por defecto en ubuntu
              scriptLocation: "inlineScript"
              inlineScript: "az webapp log config --name $(webAppName) --resource-group $(resourceGroup) --application-logging filesystem --level verbose"

          # Configurar App Service (wkhtmltopdf y gunicorn)
          - task: AzureAppServiceSettings@1
            displayName: "Configure App Settings and Startup"
            inputs:
              azureSubscription: "$(azureServiceConnectionId)"
              appName: "$(webAppName)"
              resourceGroupName: "$(resourceGroup)"
              appSettings: |
                [
                  {"name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true", "slotSetting": false},
                  {"name": "WEBSITES_PORT", "value": "8000", "slotSetting": false}
                ]
              # Comando de inicio: Instala wkhtmltopdf y luego inicia la app
              startupCommand: "apt-get update && apt-get install -y wkhtmltopdf && gunicorn --bind=0.0.0.0:8000 --timeout 600 app:app"

          # Despliegue
          - task: AzureWebApp@1
            displayName: "Deploy code to Azure Web App"
            inputs:
              azureSubscription: "$(azureServiceConnectionId)"
              appType: "webAppLinux"
              appName: "$(webAppName)"
              package: "$(Pipeline.Workspace)/drop/drop.zip"
              deploymentMethod: "zipDeploy"
              runtimeStack: "PYTHON|3.10"