# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one that's appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '956b817f-06c4-418d-98a3-b599810549b5'

  # Web app name
  webAppName: 'mi-flask-app-2025'

  # Agent VM image name (Comentada o eliminada)
  # vmImageName: 'ubuntu-latest' 

  # Environment name
  environmentName: 'mi-flask-app-2025'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  pythonVersion: '3.10' # Versión de Python de Azure App Service

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool: Default  # Usar el agente autohospedado 'Default'
    steps:
    
    # --- CORRECCIÓN DE GIT: fetchDepth: 0 ---
    - checkout: self
      fetchDepth: 0  # Soluciona los problemas de autenticación de Git (exit code 128)
    # ----------------------------------------

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'

    # --- CORRECCIÓN FINAL DE ACTIVACIÓN DE VENV PARA CMD (Sintaxis validada) ---
    - script: |
        python -m venv antenv
        .\antenv\Scripts\activate.bat # <--- COMANDO DE ACTIVACIÓN CMD
        python -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"
      # Quitamos 'shell: cmd' para evitar el error de sintaxis 'Unexpected value 'shell''. 
      # El script por defecto usa la shell nativa (CMD), por lo que esto debería funcionar ahora.
    # ---------------------------------------------------------------------------

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: Default  # Usar el agente autohospedado 'Default'
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          # --- CORRECCIÓN PARA HARD LINKING (Permisos de Disco D:\) ---
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Build Artifact (No Hard Link)'
            inputs:
              artifactName: 'drop'
              # Este parámetro fuerza una copia en lugar de hard link, solucionando el error 'Hard linking failed'
              preferSymlinks: false 
              targetPath: '$(Pipeline.Workspace)/drop'
          # ----------------------------------------------------------------------

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python version'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : mi-flask-app-2025'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              # La ruta apunta al paquete descargado por la tarea anterior
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'